INSERT INTO cms_campo(id, nombre) VALUES
( 1, 'cliente_id'),
( 2, 'cliente.documento_tipo_id'),
( 3, 'cliente.documento'),
( 4, 'cliente.fecha_nacimiento'),
( 5, 'cliente.nacionalidad_id'),
( 6, 'cliente.correo'),
( 7, 'provincia_id'),
( 8, 'localidad_id'),
( 9, 'codigo_postal'),
(10, 'direccion_id'),
(11, 'direccion_tipo_id'),
(12, 'direccion_numero'),
(13, 'direccion_piso'),
(14, 'direccion_puerta'),
(15, 'venta_modalidad_id'),
(16, 'telefonos'),
(17, ''),
(18, ''),
(19, ''),
(20, ''),
(21, ''),
(22, ''),
(23, ''),
(24, ''),
(25, ''),
(26, ''),
(27, ''),
(28, ''),
(29, ''),
;

INSERT INTO cms_campo_campania(id, campo_id, campania) VALUES
