DROP TABLE IF EXISTS test;
CREATE TABLE test (
  id INT(11) NOT NULL AUTO_INCREMENT,
  fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  booleano TINYINT(1) NOT NULL,
  texto VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO test VALUES (NULL,'2016-01-16 14:52:41',1,'perú'),(NULL,'2016-01-16 14:52:41',0,'áááááá');
